import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pageId = children && (children as any).props && (children as any).props.pageId;

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar pageId={pageId} />
        {children}
        <Footer/>
        </body>
    </html>
  );
}
